import { execFileSync, spawn } from 'node:child_process'
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
const SOURCE = 'resources/icon.svg'
const OUTPUT = 'resources/icon.icns'
const TRAY_SOURCE = 'resources/tray.svg'
const TRAY_OUTPUT = 'src/main/trayIcon.ts'
const PORT = 8732

const RENDITIONS = [
  [16, 'icon_16x16'],
  [32, 'icon_16x16@2x'],
  [32, 'icon_32x32'],
  [64, 'icon_32x32@2x'],
  [128, 'icon_128x128'],
  [256, 'icon_128x128@2x'],
  [256, 'icon_256x256'],
  [512, 'icon_256x256@2x'],
  [512, 'icon_512x512'],
  [1024, 'icon_512x512@2x']
]

if (!existsSync(CHROME)) {
  console.error(`Google Chrome is required to rasterise ${SOURCE} and was not found at ${CHROME}.`)
  process.exit(1)
}

const work = mkdtempSync(join(tmpdir(), 'wd-icon-'))
const page = join('resources', '.icon-render.html')
writeFileSync(
  page,
  '<!doctype html><meta charset="utf-8">' +
    '<style>html,body{margin:0;background:transparent}img{display:block;width:1024px;height:1024px}</style>' +
    '<img src="icon.svg">'
)

const server = spawn('python3', ['-m', 'http.server', String(PORT)], {
  cwd: 'resources',
  stdio: 'ignore'
})

async function waitForServer() {
  for (let attempt = 0; attempt < 40; attempt += 1) {
    try {
      const response = await fetch(`http://localhost:${PORT}/.icon-render.html`)
      if (response.ok) return
    } catch {
      /* not up yet */
    }
    await new Promise((resolve) => setTimeout(resolve, 100))
  }
  throw new Error('local server did not start')
}

try {
  await waitForServer()
  const master = join(work, 'icon_1024.png')
  execFileSync(CHROME, [
    '--headless',
    '--disable-gpu',
    '--default-background-color=00000000',
    '--hide-scrollbars',
    '--virtual-time-budget=3000',
    '--window-size=1024,1024',
    `--screenshot=${master}`,
    `http://localhost:${PORT}/.icon-render.html`
  ])

  const iconset = join(work, 'icon.iconset')
  execFileSync('mkdir', ['-p', iconset])
  for (const [size, name] of RENDITIONS) {
    execFileSync('sips', ['-z', String(size), String(size), master, '--out', join(iconset, `${name}.png`)])
  }
  execFileSync('iconutil', ['-c', 'icns', iconset, '-o', OUTPUT])
  console.log(`wrote ${OUTPUT} from ${SOURCE}`)

  writeFileSync(
    page,
    '<!doctype html><meta charset="utf-8">' +
      '<style>html,body{margin:0;background:transparent}img{display:block;width:32px;height:32px}</style>' +
      '<img src="tray.svg">'
  )
  const trayMaster = join(work, 'tray_32.png')
  execFileSync(CHROME, [
    '--headless',
    '--disable-gpu',
    '--default-background-color=00000000',
    '--hide-scrollbars',
    '--virtual-time-budget=2000',
    '--window-size=32,32',
    `--screenshot=${trayMaster}`,
    `http://localhost:${PORT}/.icon-render.html`
  ])

  const at1x = join(work, 'tray_16.png')
  execFileSync('sips', ['-z', '16', '16', trayMaster, '--out', at1x])
  const encode = (file) => readFileSync(file).toString('base64')
  writeFileSync(
    TRAY_OUTPUT,
    '// Generated by scripts/make-icon.mjs from ' + TRAY_SOURCE + ' — do not edit by hand.\n' +
      '// Inlined so the menu bar icon needs no packaging path that differs between dev and the\n' +
      '// packaged app.\n' +
      'export const TRAY_ICON_1X = \'data:image/png;base64,' + encode(at1x) + '\'\n' +
      'export const TRAY_ICON_2X = \'data:image/png;base64,' + encode(trayMaster) + '\'\n'
  )
  console.log(`wrote ${TRAY_OUTPUT} from ${TRAY_SOURCE}`)
} finally {
  server.kill()
  rmSync(page, { force: true })
  rmSync(work, { recursive: true, force: true })
}
